Repository labs-ruby/homeworks-2020, pull requests merged in 2020-03, with the labels that each got.

#9 HW01: solutions by Volovenko
  HW01/Vadim_Volovenko/vadim_volovenko_hw_01_t_01.rb
  HW01/Vadim_Volovenko/vadim_volovenko_hw_01_t_02.rb
  HW01/Vadim_Volovenko/vadim_volovenko_hw_01_t_03.rb
Labels: reviewed

#10 homework number one
  HW01/Vladimir_Sereda/vladimir_sereda_hw_01_t_01.rb
  HW01/Vladimir_Sereda/vladimir_sereda_hw_01_t_02.rb
  HW01/Vladimir_Sereda/vladimir_sereda_hw_01_t_03.rb
Labels: reviewed

#12 My hw 01
  HW01/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_01_t_01.rb
  HW01/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_01_t_02.rb
  HW01/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_01_t_03.rb
Labels: reviewed

#14 Hw 01
  HW01/Ivan_Papushoi/ivan_papushoi_hw_01_t_01.rb
  HW01/Ivan_Papushoi/ivan_papushoi_hw_01_t_02.rb
  HW01/Ivan_Papushoi/ivan_papushoi_hw_01_t_03.rb
Labels: reviewed

#5 HW1: solutions by Hrybinyk
  HW01/Igor_Hrybinyk/igor_hrybinyk_hw_01_t_01.rb
  HW01/Igor_Hrybinyk/igor_hrybinyk_hw_01_t_02.rb
  HW01/Igor_Hrybinyk/igor_hrybinyk_hw_01_t_03.rb
Labels: reviewed

#18 add my HW01
  HW01/Dzmitry_Neverov/dzmitry_neverov_hw_01_t_01.rb
  HW01/Dzmitry_Neverov/dzmitry_neverov_hw_01_t_02.rb
  HW01/Dzmitry_Neverov/dzmitry_neverov_hw_01_t_03.rb
Labels: reviewed

#28 Implement tasks homework_01
  HW01/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_01_t_01.rb
  HW01/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_01_t_02.rb
  HW01/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_01_t_03.rb
Labels: reviewed

#22 HW01 by Oleg Kazak
  HW01/oleg_kazak/oleg_kazak_hw_01_t_01.rb
  HW01/oleg_kazak/oleg_kazak_hw_02_t_02.rb
  HW01/oleg_kazak/oleg_kazak_hw_03_t_03.rb
Labels: reviewed

#38 HW02 by Ekaterina Vashkevich
  HW02/Ekaterina_Vashkevich/data_t_01.txt
  HW02/Ekaterina_Vashkevich/data_t_02.txt
  HW02/Ekaterina_Vashkevich/data_t_03.txt
  HW02/Ekaterina_Vashkevich/ekaterina_vashkevich_hw_02_t_01.rb
  HW02/Ekaterina_Vashkevich/ekaterina_vashkevich_hw_02_t_02.rb
  HW02/Ekaterina_Vashkevich/ekaterina_vashkevich_hw_02_t_03.rb
  HW02/Ekaterina_Vashkevich/ekaterina_vashkevich_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#46 HW02 by Vladimir Sereda
  HW02/Vladimir_Sereda/logs/logs_ts1.txt
  HW02/Vladimir_Sereda/logs/logs_ts2.txt
  HW02/Vladimir_Sereda/logs/logs_ts3.txt
  HW02/Vladimir_Sereda/vladimir_sereda_hw_02_t_01.rb
  HW02/Vladimir_Sereda/vladimir_sereda_hw_02_t_02.rb
  HW02/Vladimir_Sereda/vladimir_sereda_hw_02_t_03.rb
  HW02/Vladimir_Sereda/vladimir_sereda_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4, 🐩?

#37 [HM-02] By Mikhail Sauchuk
  HW02/Mikhail_Sauchuk/bash.log
  HW02/Mikhail_Sauchuk/debug.log
  HW02/Mikhail_Sauchuk/mikhail_sauchuk_hw_02_t_01.rb
  HW02/Mikhail_Sauchuk/mikhail_sauchuk_hw_02_t_02.rb
  HW02/Mikhail_Sauchuk/mikhail_sauchuk_hw_02_t_03.rb
  HW02/Mikhail_Sauchuk/mikhail_sauchuk_hw_02_t_04.rb
Labels: approved_task1, approved_task4

#20 HW02: solutions by Zalyotov
  HW02/Alexey_Zalyotov/alexey_zalyotov_hw_02_t_01.rb
  HW02/Alexey_Zalyotov/alexey_zalyotov_hw_02_t_02.rb
  HW02/Alexey_Zalyotov/alexey_zalyotov_hw_02_t_04.rb
  HW02/Alexey_Zalyotov/fixtures/data_hw_02_t_01.txt
  HW02/Alexey_Zalyotov/fixtures/data_hw_02_t_02.txt
  HW02/Alexey_Zalyotov/fixtures/data_hw_02_t_03.txt
  HW02/Alexey_Zalyotov/hw_02_t_03/alexey_zalyotov_hw_02_t_03.rb
  HW02/Alexey_Zalyotov/hw_02_t_03/fixtures/data_hw02t03.txt
  HW02/Alexey_Zalyotov/hw_02_t_03/lib/duration_calculator.rb
  HW02/Alexey_Zalyotov/hw_02_t_03/lib/log_formatter.rb
  HW02/Alexey_Zalyotov/hw_02_t_03/lib/log_reader.rb
  HW02/Alexey_Zalyotov/hw_02_t_03/lib/output_printer.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#35 HW 02 by Alexandr Korzun
  HW02/Aliaksandr_Korzun/.rubocop.yml
  HW02/Aliaksandr_Korzun/aliaksandr_korzun_hw_02_t_01.rb
  HW02/Aliaksandr_Korzun/aliaksandr_korzun_hw_02_t_02.rb
  HW02/Aliaksandr_Korzun/aliaksandr_korzun_hw_02_t_03.rb
  HW02/Aliaksandr_Korzun/aliaksandr_korzun_hw_02_t_04.rb
  HW02/Aliaksandr_Korzun/logfile.txt
  HW02/Aliaksandr_Korzun/logfile_task_3.txt
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#48 Implement tasks homework_02
  HW02/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_02_t_01.rb
  HW02/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_02_t_02.rb
  HW02/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_02_t_03.rb
  HW02/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#39 HW02 by Vadim Volovenko
  HW02/Vadim_Volovenko/fixtures/data_for_t_01.txt
  HW02/Vadim_Volovenko/fixtures/data_for_t_03.txt
  HW02/Vadim_Volovenko/vadim_volovenko_hw_02_t_01.rb
  HW02/Vadim_Volovenko/vadim_volovenko_hw_02_t_02.rb
  HW02/Vadim_Volovenko/vadim_volovenko_hw_02_t_03.rb
  HW02/Vadim_Volovenko/vadim_volovenko_hw_02_t_04.rb
Labels: approved_task1, approved_task4

#44 HW02 by Arthur Bohan
  HW02/Arthur_Bohan/arthur_bohan_hw_02_t_01.rb
  HW02/Arthur_Bohan/arthur_bohan_hw_02_t_02.rb
  HW02/Arthur_Bohan/arthur_bohan_hw_02_t_03.rb
  HW02/Arthur_Bohan/arthur_bohan_hw_02_t_04.rb
  HW02/Arthur_Bohan/input_hw_02_t_01.txt
  HW02/Arthur_Bohan/input_hw_02_t_02.txt
  HW02/Arthur_Bohan/input_hw_02_t_03.txt
Labels: approved_task1, approved_task2, approved_task4

#41 HW02 by Kate Fedotova
  HW02/Kate_Fedotova/kate_fedotova_hw_02_t_01.rb
  HW02/Kate_Fedotova/kate_fedotova_hw_02_t_02.rb
  HW02/Kate_Fedotova/kate_fedotova_hw_02_t_03.rb
  HW02/Kate_Fedotova/kate_fedotova_hw_02_t_04.rb
  HW02/Kate_Fedotova/task_1.txt
  HW02/Kate_Fedotova/task_2.txt
  HW02/Kate_Fedotova/task_3.txt
Labels: approved_task2, approved_task3, approved_task4, reviewed_task1

#33 Hw_02 by Ivan_Papushoi
  HW02/Ivan_Papushoi/ivan_papushoi_hw_02_t_01.rb
  HW02/Ivan_Papushoi/ivan_papushoi_hw_02_t_02.rb
  HW02/Ivan_Papushoi/ivan_papushoi_hw_02_t_03.rb
  HW02/Ivan_Papushoi/ivan_papushoi_hw_02_t_04.rb
  HW02/Ivan_Papushoi/user_input_t01_t02.txt
  HW02/Ivan_Papushoi/user_input_t03.txt
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#43 HW02 by Ilya Gribko
  HW02/Ilya_Gribko/data_test_with_errors.log
  HW02/Ilya_Gribko/data_test_without_errors.log
  HW02/Ilya_Gribko/debug_data_test.log
  HW02/Ilya_Gribko/ilya_gribko_hw_02_t_01.rb
  HW02/Ilya_Gribko/ilya_gribko_hw_02_t_02.rb
  HW02/Ilya_Gribko/ilya_gribko_hw_02_t_03.rb
  HW02/Ilya_Gribko/ilya_gribko_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#24 HW02 by Ilia Aksenov
  HW02/Ilia_Aksenov/ilia_aksenov_hw_02_t_01.rb
  HW02/Ilia_Aksenov/ilia_aksenov_hw_02_t_02.rb
  HW02/Ilia_Aksenov/ilia_aksenov_hw_02_t_03.rb
  HW02/Ilia_Aksenov/ilia_aksenov_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#34 HW02: solutions by Tatsiana Zenkovich
  HW02/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_02_t_01.rb
  HW02/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_02_t_02.rb
  HW02/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_02_t_03.rb
  HW02/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#45 [HW-2]Regex
  HW02/Yuliya_Bukhtik/data/log_file_task_01.txt
  HW02/Yuliya_Bukhtik/data/log_file_task_02.txt
  HW02/Yuliya_Bukhtik/data/log_file_task_03.txt
  HW02/Yuliya_Bukhtik/log_file.txt
  HW02/Yuliya_Bukhtik/yuliya_bukhtik_hw_02_t_01.rb
  HW02/Yuliya_Bukhtik/yuliya_bukhtik_hw_02_t_02.rb
  HW02/Yuliya_Bukhtik/yuliya_bukhtik_hw_02_t_03.rb
  HW02/Yuliya_Bukhtik/yuliya_bukhtik_hw_02_t_04.rb
Labels: approved_task1, approved_task2, approved_task3, approved_task4

#47 My hw 02
  HW02/Dzmitry_Neverov/task1/handler.rb
  HW02/Dzmitry_Neverov/task1/logs_hw_02_t_01.txt
  HW02/Dzmitry_Neverov/task2/logs_hw_02_t_02.txt
  HW02/Dzmitry_Neverov/task2/logs_reader.rb
  HW02/Dzmitry_Neverov/task2/logs_validator.rb
  HW02/Dzmitry_Neverov/task2/start.rb
  HW02/Dzmitry_Neverov/task3/line_search.rb
  HW02/Dzmitry_Neverov/task3/logs_hw_02_t_03.txt
  HW02/Dzmitry_Neverov/task3/logs_reader.rb
  HW02/Dzmitry_Neverov/task3/start.rb
  HW02/Dzmitry_Neverov/task3/time_calculator.rb
  HW02/Dzmitry_Neverov/task4/h2_t4.rb
Labels: approved_task1, approved_task2, approved_task4, reviewed_task3
