Repository labs-ruby/homeworks-2020, pull requests merged in 2020-04, with the labels that each got.

#49 HW02 Pavel Karenda
  HW02/Pavel_Karenda/.gitignore
  HW02/Pavel_Karenda/README.md
  HW02/Pavel_Karenda/input-data.txt
  HW02/Pavel_Karenda/logs_with_error.txt
  HW02/Pavel_Karenda/logs_with_error2.txt
  HW02/Pavel_Karenda/pavel_karenda_hw_02_t_01.rb
  HW02/Pavel_Karenda/pavel_karenda_hw_02_t_02.rb
  HW02/Pavel_Karenda/pavel_karenda_hw_02_t_03.rb
  HW02/Pavel_Karenda/pavel_karenda_hw_02_t_04.rb
Labels: reviewed_task1, reviewed_task2, reviewed_task3, reviewed_task4

#50 Unbelievable task solving (part 2)
  HW02/Dima_Yakutovich/dima_yakutovich_hw_02_t_01.rb
  HW02/Dima_Yakutovich/dima_yakutovich_hw_02_t_02.rb
  HW02/Dima_Yakutovich/dima_yakutovich_hw_02_t_03.rb
  HW02/Dima_Yakutovich/dima_yakutovich_hw_02_t_04.rb
  HW02/Dima_Yakutovich/input_task03.txt
  HW02/Dima_Yakutovich/logs.txt
  HW02/Dima_Yakutovich/readme.md
Labels: approved_task4, reviewed_task1

#54 HW03: solutions by Zalyotov
  HW03/Alexey_Zalyotov/app.rb
  HW03/Alexey_Zalyotov/lib/mentor.rb
  HW03/Alexey_Zalyotov/lib/notification.rb
  HW03/Alexey_Zalyotov/lib/person.rb
  HW03/Alexey_Zalyotov/lib/repo.rb
  HW03/Alexey_Zalyotov/lib/student.rb
  HW03/Alexey_Zalyotov/lib/task.rb
Labels: original, reviewed

#55 HW03 by Vashkevich Ekaterina
  HW03/Ekaterina_Vashkevich/app.rb
  HW03/Ekaterina_Vashkevich/homework.rb
  HW03/Ekaterina_Vashkevich/mentor.rb
  HW03/Ekaterina_Vashkevich/notification.rb
  HW03/Ekaterina_Vashkevich/student.rb
Labels: original

#59 HW03 by Kate Fedotova
  HW03/Kate Fedotova/app.rb
  HW03/Kate Fedotova/homework.rb
  HW03/Kate Fedotova/mentor.rb
  HW03/Kate Fedotova/notification.rb
  HW03/Kate Fedotova/student.rb
Labels: reviewed

#67 HW03: Arthur Bohan
  HW03/Arthur_Bohan/.rubocop.yml
  HW03/Arthur_Bohan/app.rb
  HW03/Arthur_Bohan/homework.rb
  HW03/Arthur_Bohan/mentor.rb
  HW03/Arthur_Bohan/notification.rb
  HW03/Arthur_Bohan/student.rb
Labels: duplicate, reviewed

#66 HW3: answers by Zavaliuk
  HW03/Anton_Zavaliuk/README.md
  HW03/Anton_Zavaliuk/app.rb
  HW03/Anton_Zavaliuk/lib/mentor.rb
  HW03/Anton_Zavaliuk/lib/postgres/api.rb
  HW03/Anton_Zavaliuk/lib/student.rb
Labels: original, reviewed

#68 HW_03 by Ivan_Papushoi
  HW03/Ivan_Papushoi/app.rb
  HW03/Ivan_Papushoi/mentor.rb
  HW03/Ivan_Papushoi/student.rb
  HW03/Ivan_Papushoi/task.rb
Labels: original

#57 [HM-03] By Mikhail Sauchuk
  HW03/Mikhail_Sauchuk/abstract_observer.rb
  HW03/Mikhail_Sauchuk/homework.rb
  HW03/Mikhail_Sauchuk/mentor.rb
  HW03/Mikhail_Sauchuk/mikhail_sauchuk_app.rb
  HW03/Mikhail_Sauchuk/student.rb
Labels: original, reviewed

#56 HW03: by Vadim Volovenko
  HW03/Vadim_Volovenko/app.rb
  HW03/Vadim_Volovenko/homework.rb
  HW03/Vadim_Volovenko/mentor.rb
  HW03/Vadim_Volovenko/notifications.rb
  HW03/Vadim_Volovenko/student.rb
Labels: partially_duplicate, reviewed

#53 HW 03 by Tatsiana_Zenkovich
  HW03/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_03_t_01/app.rb
  HW03/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_03_t_01/mentor.rb
  HW03/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_03_t_01/student.rb
  HW03/Tatsiana_Zenkovich/tatsiana_zenkovich_hw_03_t_01/task.rb
Labels: original

#62 Implement tasks homework_03
  HW03/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_03.rb
  HW03/Anastasiya_Gavrilik/lib/app/homework.rb
  HW03/Anastasiya_Gavrilik/lib/app/human.rb
  HW03/Anastasiya_Gavrilik/lib/app/mentor.rb
  HW03/Anastasiya_Gavrilik/lib/app/run.rb
  HW03/Anastasiya_Gavrilik/lib/app/student.rb
  HW03/Anastasiya_Gavrilik/lib/config.rb
Labels: original, reviewed

#69 HW03 Pavel Karenda
  HW03/Pavel_Karenda/homework.rb
  HW03/Pavel_Karenda/main.rb
  HW03/Pavel_Karenda/mentor.rb
  HW03/Pavel_Karenda/student.rb
Labels: duplicate

#52 HW3: solution by Hrybinyk
  HW03/Igor_Hrybinyk/README.md
  HW03/Igor_Hrybinyk/app.rb
  HW03/Igor_Hrybinyk/lib/homework.rb
  HW03/Igor_Hrybinyk/lib/mentor.rb
  HW03/Igor_Hrybinyk/lib/student.rb
  HW03/Igor_Hrybinyk/observers/mentor_observer.rb
  HW03/Igor_Hrybinyk/observers/student_observer.rb
Labels: original

#76 HW 04 solution by Tatsiana_Zenkovich
  HW04/Tatsiana_Zenkovich/spec/my_methods.rb
  HW04/Tatsiana_Zenkovich/spec/my_methods_spec.rb
Labels: reviewed_test1

#79 HW04 solutions by Vashkevich Ekaterina
  HW04/Ekaterina_Vashkevich/.rspec
  HW04/Ekaterina_Vashkevich/Gemfile
  HW04/Ekaterina_Vashkevich/Gemfile.lock
  HW04/Ekaterina_Vashkevich/lib/my_method.rb
  HW04/Ekaterina_Vashkevich/spec/my_method_spec.rb
  HW04/Ekaterina_Vashkevich/spec/spec_helper.rb
Labels: rubocop-rspec

#73 HW04: solutions by Zalyotov
  HW04/Alexey_Zalyotov/.gitignore
  HW04/Alexey_Zalyotov/.rspec
  HW04/Alexey_Zalyotov/Gemfile
  HW04/Alexey_Zalyotov/Gemfile.lock
  HW04/Alexey_Zalyotov/app.rb
  HW04/Alexey_Zalyotov/lib/my_module.rb
  HW04/Alexey_Zalyotov/spec/my_module_spec.rb
  HW04/Alexey_Zalyotov/spec/spec_helper.rb
Labels: reviewed_test1

#82 HW-04 by Arthur_Bohan
  HW04/Arthur_Bohan/.rubocop.yml
  HW04/Arthur_Bohan/my_array_methods.rb
  HW04/Arthur_Bohan/spec/my_array_methods_spec.rb
  HW04/Arthur_Bohan/spec/spec_helper.rb
Labels: rubocop-rspec

#77 HW_04 by Ivan Papushoi
  HW04/Ivan_Papushoi/.rubocop.yml
  HW04/Ivan_Papushoi/Gemfile
  HW04/Ivan_Papushoi/Gemfile.lock
  HW04/Ivan_Papushoi/array_my_methods_spec.rb
  HW04/Ivan_Papushoi/ivan_papushoi_hw04.rb
Labels: reviewed_test1, rubocop-rspec

#81 Implement tasks homework_04
  HW04/Anastasiya_Gavrilik/.rspec
  HW04/Anastasiya_Gavrilik/anastasiya_gavrilik_hw_04.rb
  HW04/Anastasiya_Gavrilik/lib/config.rb
  HW04/Anastasiya_Gavrilik/lib/custom/my_each.rb
  HW04/Anastasiya_Gavrilik/lib/custom/my_map.rb
  HW04/Anastasiya_Gavrilik/lib/custom/my_select.rb
  HW04/Anastasiya_Gavrilik/lib/custom/run.rb
  HW04/Anastasiya_Gavrilik/spec/custom/my_each_spec.rb
  HW04/Anastasiya_Gavrilik/spec/custom/my_map_spec.rb
  HW04/Anastasiya_Gavrilik/spec/custom/my_select_spec.rb
  HW04/Anastasiya_Gavrilik/spec/spec_helper.rb
Labels: rubocop-rspec

#74 HW4: solutions by Hrybinyk
  HW04/Igor_Hrybinyk/.rspec
  HW04/Igor_Hrybinyk/Gemfile
  HW04/Igor_Hrybinyk/Gemfile.lock
  HW04/Igor_Hrybinyk/app.rb
  HW04/Igor_Hrybinyk/my_methods.rb
  HW04/Igor_Hrybinyk/spec/array_my_each_spec.rb
  HW04/Igor_Hrybinyk/spec/array_my_map_spec.rb
  HW04/Igor_Hrybinyk/spec/array_my_select_spec.rb
  HW04/Igor_Hrybinyk/spec/spec_helper.rb
Labels: reviewed_test1

#83 HW 04 by Vladimir Sereda
  HW04/Vladimir_Sereda/.rubocop.yml
  HW04/Vladimir_Sereda/module.rb
  HW04/Vladimir_Sereda/module_spec.rb
Labels: rubocop-rspec

#86 HW04 by Ilya Gribko
  HW04/Ilya_Gribko/.rspec
  HW04/Ilya_Gribko/Gemfile
  HW04/Ilya_Gribko/Gemfile.lock
  HW04/Ilya_Gribko/app.rb
  HW04/Ilya_Gribko/lib/my_methods.rb
  HW04/Ilya_Gribko/spec/array_my_methods_spec.rb
  HW04/Ilya_Gribko/spec/shared/iterator_spec.rb
  HW04/Ilya_Gribko/spec/spec_helper.rb
Labels: rubocop-rspec

#94 HW-04_done
  HW04/Yuliya_Bukhtik/array.rb
  HW04/Yuliya_Bukhtik/my_module.rb
  HW04/Yuliya_Bukhtik/my_module_spec.rb
Labels: rubocop-rspec

#75 HW4: answers by Zavaliuk
  HW04/Anton_Zavaliuk/lib/array.rb
  HW04/Anton_Zavaliuk/lib/custom_array.rb
  HW04/Anton_Zavaliuk/task1.rb
  HW04/Anton_Zavaliuk/tests/array_spec.rb
  HW04/spec/spec_helper.rb
Labels: rubocop-rspec

#60 HW03 by Ilia Aksenov
  HW01/Ilia_Aksenov/ilia_aksenov_hw_01_t_01.rb
  HW03/Ilia_Aksenov/mentor.rb
  HW03/Ilia_Aksenov/student.rb
Labels: original
